# CircleCI configuration file

version: 2.1

orbs:
  snyk: snyk/snyk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/node:lts
    resource_class: xlarge
    steps:
      - checkout
      - run: echo "Build finished."

  jest-unit-tests:
    docker:
      - image: cimg/node:lts
    resource_class: xlarge
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Install node mods
          command: npm ci
      - run:
          name: Run tests
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: junit

  snyk-sast:
    docker:
      - image: cimg/node:lts
    resource_class: xlarge
    steps:
      - checkout
      - run: npm ci
      - snyk/scan

workflows:
  cool-workflow:
    jobs:
      - build
      - jest-unit-tests
      - snyk-sast
